#!/usr/bin/env Rscript
# Regenerate all API-backed mock data files in tests/testthat/mocks/.
#
# Run from the package root whenever the API schema changes or the test
# fixtures need refreshing with up-to-date data:
#
#   Rscript tests/testthat/regenerate_mocks.R
#
# Each primary mock object is re-fetched from the live API and serialised with
# dput().  Alias variables and hand-crafted derived mocks (e.g.
# mock_plot_data_with_synonym) are appended verbatim and are NOT re-fetched.
#
# To target a non-production API, set the VB_BASE_URL environment variable:
#
#   VB_BASE_URL=https://api.dev.vegbank.org Rscript tests/testthat/regenerate_mocks.R

library(vegbankr)

if (nzchar(Sys.getenv("VB_BASE_URL"))) {
  vb_set_base_url(Sys.getenv("VB_BASE_URL"))
}

message("Using base URL: ", vegbankr::vb_get_base_url())

mocks_dir <- file.path("tests", "testthat", "mocks")
if (!dir.exists(mocks_dir)) {
  stop("Run this script from the package root directory.")
}

# ── Helpers ──────────────────────────────────────────────────────────────────

# Serialise an R object to a variable assignment using dput().
# Returns a character vector of lines suitable for writeLines().
as_assignment <- function(var_name, obj) {
  lines <- capture.output(dput(obj))
  lines[1] <- paste0(var_name, " <- ", lines[1])
  lines
}

# Write a mock file, printing a progress message.
write_mock_file <- function(filename, lines) {
  path <- file.path(mocks_dir, filename)
  writeLines(lines, path)
  message("  Written: ", path)
}

# Build lines for the auto-generated file header.
file_header <- function(description, fn_name) {
  c(
    paste0("# Mock ", description, " data for tests"),
    paste0("# Auto-generated by tests/testthat/regenerate_mocks.R"),
    paste0("# All mocks are derived from real ", fn_name, "() API responses."),
    ""
  )
}

# ── community_classifications.R ──────────────────────────────────────────────
message("Fetching community classifications...")

cl1943   <- vegbankr::vb_get_community_classifications("cl.1943",   detail = "full", with_nested = TRUE)
cl2358   <- vegbankr::vb_get_community_classifications("cl.2358",   detail = "full", with_nested = TRUE)
cl167392 <- vegbankr::vb_get_community_classifications("cl.167392", detail = "full", with_nested = TRUE)

write_mock_file("community_classifications.R", c(
  file_header("community classification", "vegbankr::vb_get_community_classifications"),
  "# ── cl.1943 · BADL.119 · ob.3407 ───────────────────────────────────────────",
  as_assignment("mock_comm_class_cl1943", cl1943),
  "",
  "# ── cl.2358 · ISRO.020 · ob.3884 ───────────────────────────────────────────",
  as_assignment("mock_comm_class_cl2358", cl2358),
  "",
  "# ── cl.167392 · OLYM.Z.725.0002 · ob.206458 ─────────────────────────────────",
  as_assignment("mock_comm_class_cl167392", cl167392),
  "",
  "# Backward-compatible aliases",
  "mock_comm_class_data <- mock_comm_class_cl1943",
  "mock_comm_class_interpretations <- mock_comm_class_cl1943$interpretations[[1]]",
  "mock_comm_class_contributors <- mock_comm_class_cl1943$contributors[[1]]"
))

# ── community_concepts.R ─────────────────────────────────────────────────────
message("Fetching community concepts...")

cc47882 <- vegbankr::vb_get_community_concepts("cc.47882", detail = "full", with_nested = TRUE)
cc38611 <- vegbankr::vb_get_community_concepts("cc.38611", detail = "full", with_nested = TRUE)
cc133   <- vegbankr::vb_get_community_concepts("cc.133",   detail = "full", with_nested = TRUE)

write_mock_file("community_concepts.R", c(
  file_header("community concept", "vegbankr::vb_get_community_concepts"),
  "# ── cc.47882 · CEGL007230 · Quercus alba - Quercus (rubra, montana) Forest ───",
  as_assignment("mock_comm_concept_cegl007230", cc47882),
  "",
  "# ── cc.38611 · Brachypodium distachyon – Bromus diandrus / Quercus douglasii ─",
  as_assignment("mock_comm_concept_brachypodium", cc38611),
  "",
  "# ── cc.133 · VII · Sparse Vegetation Class ───────────────────────────────────",
  as_assignment("mock_comm_concept_vii", cc133),
  "",
  "# Backward-compatible alias",
  "mock_comm_concept_data <- mock_comm_concept_cegl007230"
))

# ── cover_methods.R ──────────────────────────────────────────────────────────
message("Fetching cover methods...")

cm79   <- vegbankr::vb_get_cover_methods("cm.79",   detail = "full", with_nested = TRUE)
cm1630 <- vegbankr::vb_get_cover_methods("cm.1630", detail = "full", with_nested = TRUE)
cm1    <- vegbankr::vb_get_cover_methods("cm.1",    detail = "full", with_nested = TRUE)

write_mock_file("cover_methods.R", c(
  file_header("cover method", "vegbankr::vb_get_cover_methods"),
  "# ── cm.79 · NPS CoverMethod ──────────────────────────────────────────────────",
  as_assignment("mock_cover_method_cm79", cm79),
  "",
  "# ── cm.1630 · Domin Cover Scale ─────────────────────────────────────────────",
  as_assignment("mock_cover_method_cm1630", cm1630),
  "",
  "# ── cm.1 · Carolina Vegetation Survey ───────────────────────────────────────",
  as_assignment("mock_cover_method_cm1", cm1),
  "",
  "# Backward-compatible alias",
  "mock_cover_method_data <- mock_cover_method_cm1"
))

# ── parties.R ────────────────────────────────────────────────────────────────
message("Fetching parties...")

py415    <- vegbankr::vb_get_parties("py.415",    detail = "full")
py17     <- vegbankr::vb_get_parties("py.17",     detail = "full")
py199146 <- vegbankr::vb_get_parties("py.199146", detail = "full")

write_mock_file("parties.R", c(
  file_header("party (person/organization)", "vegbankr::vb_get_parties"),
  "# ── py.415 · Michael Jennings ───────────────────────────────────────────────",
  as_assignment("mock_party_py415", py415),
  "",
  "# ── py.17 · Jim Drake ───────────────────────────────────────────────────────",
  as_assignment("mock_party_py17", py17),
  "",
  "# ── py.199146 ────────────────────────────────────────────────────────────────",
  as_assignment("mock_party_py199146", py199146),
  "",
  "# Backward-compatible alias",
  "mock_party_data <- mock_party_py415"
))

# ── plant_concepts.R ─────────────────────────────────────────────────────────
message("Fetching plant concepts...")

pc111478 <- vegbankr::vb_get_plant_concepts("pc.111478", detail = "full", with_nested = TRUE)
pc389660 <- vegbankr::vb_get_plant_concepts("pc.389660", detail = "full", with_nested = TRUE)
pc47659  <- vegbankr::vb_get_plant_concepts("pc.47659",  detail = "full", with_nested = TRUE)

write_mock_file("plant_concepts.R", c(
  file_header("plant concept", "vegbankr::vb_get_plant_concepts"),
  "# ── pc.111478 · Acer rubrum L. (red maple, ACRU) ────────────────────────────",
  as_assignment("mock_plant_concept_acru", pc111478),
  "",
  "# ── pc.389660 · Vaccinium ────────────────────────────────────────────────────",
  as_assignment("mock_plant_concept_vaccinium", pc389660),
  "",
  "# ── pc.47659 · Pseudotsuga menziesii (PSME) ─────────────────────────────────",
  as_assignment("mock_plant_concept_psme", pc47659),
  "",
  "# Backward-compatible alias",
  "mock_plant_concept_data <- mock_plant_concept_acru"
))

# ── plot_observations.R ──────────────────────────────────────────────────────
message("Fetching plot observations...")

ob2948   <- vegbankr::vb_get_plot_observations("ob.2948",   detail = "full", with_nested = TRUE, max_taxa = 100000)
ob3776   <- vegbankr::vb_get_plot_observations("ob.3776",   detail = "full", with_nested = TRUE, max_taxa = 100000)
ob206444 <- vegbankr::vb_get_plot_observations("ob.206444", detail = "full", with_nested = TRUE, max_taxa = 100000)

write_mock_file("plot_observations.R", c(
  file_header("plot observation", "vegbankr::vb_get_plot_observations"),
  "# ── ob.2948 · ACAD.143 (Acadia NP, Maine) ───────────────────────────────────",
  as_assignment("mock_plot_data", ob2948),
  "",
  "# ── ob.3776 · GRSM.225 (Great Smoky Mountains NP) ───────────────────────────",
  as_assignment("mock_plot_data_grsm225", ob3776),
  "",
  "# ── ob.206444 · OLYM.Z.681.0003 (Olympic NP, null coords / zero taxa) ────────",
  as_assignment("mock_plot_data_olym", ob206444),
  "",
  "# ── Derived single-row variants ───────────────────────────────────────────────",
  "",
  "# Synonym notification banner: replaced observation",
  "mock_plot_data_with_synonym <- mock_plot_data",
  "mock_plot_data_with_synonym$has_observation_synonym <- TRUE",
  'mock_plot_data_with_synonym$replaced_by_ob_code <- "ob.9999"',
  "",
  "# Reference + previous observation code present",
  "mock_plot_data_with_reference <- mock_plot_data",
  'mock_plot_data_with_reference$rf_code <- "rf.501"',
  'mock_plot_data_with_reference$rf_label <- "Gawler, S. 2000."',
  'mock_plot_data_with_reference$previous_ob_code <- "ob.2100"',
  "",
  "# ── Multi-row combined mock (for table/map tests) ─────────────────────────────",
  "# Rows: ACAD.143 (Maine, public) | GRSM.225 (Tennessee, confidential, null soils)",
  "#       OLYM.Z.681.0003 (null coords, zero taxa)",
  '.nested_cols <- c("top_taxon_observations", "top_classifications", "disturbances", "soils", "named_places")',
  "",
  "mock_plot_observations_multi <- rbind(",
  "  mock_plot_data[, setdiff(names(mock_plot_data), .nested_cols)],",
  "  mock_plot_data_grsm225[, setdiff(names(mock_plot_data_grsm225), .nested_cols)],",
  "  mock_plot_data_olym[, setdiff(names(mock_plot_data_olym), .nested_cols)]",
  ")",
  "mock_plot_observations_multi$top_taxon_observations <- list(",
  "  mock_plot_data$top_taxon_observations[[1]],",
  "  mock_plot_data_grsm225$top_taxon_observations[[1]],",
  "  mock_plot_data_olym$top_taxon_observations[[1]]",
  ")",
  "mock_plot_observations_multi$top_classifications <- list(",
  "  mock_plot_data$top_classifications[[1]],",
  "  mock_plot_data_grsm225$top_classifications[[1]],",
  "  mock_plot_data_olym$top_classifications[[1]]",
  ")",
  "mock_plot_observations_multi$disturbances <- list(",
  "  mock_plot_data$disturbances[[1]],",
  "  mock_plot_data_grsm225$disturbances[[1]],",
  "  mock_plot_data_olym$disturbances[[1]]",
  ")",
  "mock_plot_observations_multi$soils <- list(",
  "  mock_plot_data$soils[[1]],",
  "  mock_plot_data_grsm225$soils[[1]],",
  "  mock_plot_data_olym$soils[[1]]",
  ")",
  "",
  "rm(.nested_cols)"
))

# ── projects.R ───────────────────────────────────────────────────────────────
message("Fetching projects...")

pj339   <- vegbankr::vb_get_projects("pj.339",   detail = "full")
pj10559 <- vegbankr::vb_get_projects("pj.10559", detail = "full")
pj11008 <- vegbankr::vb_get_projects("pj.11008", detail = "full")

write_mock_file("projects.R", c(
  file_header("project", "vegbankr::vb_get_projects"),
  "# ── pj.339 · Interior Northwest vegetation alliances ─────────────────────────",
  as_assignment("mock_project_pj339", pj339),
  "",
  "# ── pj.10559 ─────────────────────────────────────────────────────────────────",
  as_assignment("mock_project_pj10559", pj10559),
  "",
  "# ── pj.11008 ─────────────────────────────────────────────────────────────────",
  as_assignment("mock_project_pj11008", pj11008),
  "",
  "# Backward-compatible alias",
  "mock_project_data <- mock_project_pj10559"
))

# ── references.R ─────────────────────────────────────────────────────────────
message("Fetching references...")

rf36675 <- vegbankr::vb_get_references("rf.36675", detail = "full")
rf37    <- vegbankr::vb_get_references("rf.37",    detail = "full")
rf35243 <- vegbankr::vb_get_references("rf.35243", detail = "full")

write_mock_file("references.R", c(
  file_header("reference (literature citation)", "vegbankr::vb_get_references"),
  "# ── rf.36675 · NYNHP Field Form Instructions ────────────────────────────────",
  as_assignment("mock_reference_rf36675", rf36675),
  "",
  "# ── rf.37 · USDA Plants 2011 ────────────────────────────────────────────────",
  as_assignment("mock_reference_rf37", rf37),
  "",
  "# ── rf.35243 ─────────────────────────────────────────────────────────────────",
  as_assignment("mock_reference_rf35243", rf35243),
  "",
  "# Backward-compatible alias",
  "mock_reference_data <- mock_reference_rf36675"
))

# ── stratum_methods.R ────────────────────────────────────────────────────────
message("Fetching stratum methods...")

sm1   <- vegbankr::vb_get_stratum_methods("sm.1",   detail = "full", with_nested = TRUE)
sm5   <- vegbankr::vb_get_stratum_methods("sm.5",   detail = "full", with_nested = TRUE)
sm329 <- vegbankr::vb_get_stratum_methods("sm.329", detail = "full", with_nested = TRUE)

write_mock_file("stratum_methods.R", c(
  file_header("stratum method", "vegbankr::vb_get_stratum_methods"),
  "# ── sm.1 · Carolina Vegetation Survey ───────────────────────────────────────",
  as_assignment("mock_stratum_method_sm1", sm1),
  "",
  "# ── sm.5 ─────────────────────────────────────────────────────────────────────",
  as_assignment("mock_stratum_method_sm5", sm5),
  "",
  "# ── sm.329 ───────────────────────────────────────────────────────────────────",
  as_assignment("mock_stratum_method_sm329", sm329),
  "",
  "# Backward-compatible alias",
  "mock_stratum_method_data <- mock_stratum_method_sm1"
))

message("\nAll mock files regenerated successfully.")
message("Run devtools::test() to verify the updated fixtures pass all tests.")
